CREATE TABLE XXMIP.INSR_VALUE_HEADERS_ALL
(
  INSR_VALUE_HEADER_ID  NUMBER,
  VALUE_NAME            VARCHAR2(4000 BYTE),
  UPDATE_ALLOWED        VARCHAR2(1 BYTE),
  NOTE                  VARCHAR2(4000 BYTE),
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER(15),
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER(15),
  LAST_UPDATE_LOGIN     NUMBER(15)
)
TABLESPACE XXMIP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.INSR_VALUE_HEADERS_ALL_PK ON XXMIP.INSR_VALUE_HEADERS_ALL
(INSR_VALUE_HEADER_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.INSR_VALUE_HEADERS_ALL_U1 ON XXMIP.INSR_VALUE_HEADERS_ALL
(VALUE_NAME, INSR_VALUE_HEADER_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   166
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XXMIP.INSR_VALUE_HEADERS_ALL ADD (
  CONSTRAINT INSR_VALUE_HEADERS_ALL_PK
  PRIMARY KEY
  (INSR_VALUE_HEADER_ID)
  USING INDEX XXMIP.INSR_VALUE_HEADERS_ALL_PK
  ENABLE VALIDATE,
  CONSTRAINT INSR_VALUE_HEADERS_ALL_U1
  UNIQUE (VALUE_NAME, INSR_VALUE_HEADER_ID)
  USING INDEX XXMIP.INSR_VALUE_HEADERS_ALL_U1
  ENABLE VALIDATE);
