CREATE TABLE XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB
(
  LOGO_ORG_ID           VARCHAR2(50 BYTE),
  LOGO_ORG_NAME         VARCHAR2(255 BYTE),
  ORA_ORG_ID            VARCHAR2(50 BYTE),
  ORA_ORG_NAME          VARCHAR2(255 BYTE),
  LOGO_POS_ID           VARCHAR2(50 BYTE),
  LOGO_POS_NAME         VARCHAR2(255 BYTE),
  ORA_POS_ID            VARCHAR2(50 BYTE),
  ORA_POS_NAME          VARCHAR2(255 BYTE),
  LOGO_JOB_ID           VARCHAR2(50 BYTE),
  LOGO_JOB_NAME         VARCHAR2(255 BYTE),
  ORA_JOB_ID            VARCHAR2(50 BYTE),
  ORA_JOB_NAME          VARCHAR2(255 BYTE),
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  RECORD_ID             NUMBER,
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             64K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB_PK ON XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB
(RECORD_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.U_ORG_POS_JOB_ID ON XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB
(LOGO_ORG_ID, LOGO_POS_ID, LOGO_JOB_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.U_ORG_POS_JOB_NAME ON XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB
(LOGO_ORG_NAME, LOGO_POS_NAME, LOGO_JOB_NAME)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             64K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB ADD (
  CONSTRAINT MIP_LOGO_ORACLE_ORG_POS_JOB_PK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX XXMIP.MIP_LOGO_ORACLE_ORG_POS_JOB_PK
  ENABLE VALIDATE,
  CONSTRAINT U_ORG_POS_JOB_ID
  UNIQUE (LOGO_ORG_ID, LOGO_POS_ID, LOGO_JOB_ID)
  USING INDEX XXMIP.U_ORG_POS_JOB_ID
  ENABLE VALIDATE,
  CONSTRAINT U_ORG_POS_JOB_NAME
  UNIQUE (LOGO_ORG_NAME, LOGO_POS_NAME, LOGO_JOB_NAME)
  USING INDEX XXMIP.U_ORG_POS_JOB_NAME
  ENABLE VALIDATE);
