CREATE TABLE XXMIP.XLS_GLOBAL_INTERFACE_MAPPING
(
  FUNCTION_PARAM        VARCHAR2(50 BYTE)       NOT NULL,
  "SCHEMA"              VARCHAR2(50 BYTE)       NOT NULL,
  TABLE_NAME            VARCHAR2(50 BYTE)       NOT NULL,
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  RECORD_ID             NUMBER,
  XLS_COLUMN            VARCHAR2(150 BYTE)      NOT NULL,
  COLUMN_FIELD_NAME     VARCHAR2(150 BYTE)      NOT NULL,
  COLUMN_FIELD_TYPE     VARCHAR2(50 BYTE)       NOT NULL,
  ENABLED_FLAG          VARCHAR2(1 BYTE)        DEFAULT 'Y',
  RESP_ID               NUMBER                  NOT NULL,
  REQUIRED              VARCHAR2(1 BYTE),
  XLS_COLUMN_USER_NAME  VARCHAR2(500 BYTE)
)
TABLESPACE XXMIP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.INT_MAP_UX ON XXMIP.XLS_GLOBAL_INTERFACE_MAPPING
(FUNCTION_PARAM, "SCHEMA", TABLE_NAME, XLS_COLUMN, RESP_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.XLS_GLOBAL_INTERFACE_MAPPINGPK ON XXMIP.XLS_GLOBAL_INTERFACE_MAPPING
(RECORD_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XXMIP.XLS_GLOBAL_INTERFACE_MAPPING ADD (
  CONSTRAINT XLS_GLOBAL_INTERFACE_MAPPINGPK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX XXMIP.XLS_GLOBAL_INTERFACE_MAPPINGPK
  ENABLE VALIDATE);
