CREATE TABLE XXMIP.XLS_GLOBAL_SECURITY_MAPPING
(
  RESP_KEY               VARCHAR2(50 BYTE),
  FILE_PARAM             VARCHAR2(50 BYTE),
  CONCURRENT_SHORT_NAME  VARCHAR2(150 BYTE),
  RECORD_ID              NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  RESP_ID                NUMBER
)
TABLESPACE XXMIP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.XLS_GLOBAL_SECURITY_MAPPING_PK ON XXMIP.XLS_GLOBAL_SECURITY_MAPPING
(RECORD_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXMIP.XLS_SECURITY_MAP_UIX ON XXMIP.XLS_GLOBAL_SECURITY_MAPPING
(FILE_PARAM, RESP_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM APPS.XLS_GLOBAL_SECURITY_MAPPING FOR XXMIP.XLS_GLOBAL_SECURITY_MAPPING;


ALTER TABLE XXMIP.XLS_GLOBAL_SECURITY_MAPPING ADD (
  CONSTRAINT XLS_GLOBAL_SECURITY_MAPPING_PK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX XXMIP.XLS_GLOBAL_SECURITY_MAPPING_PK
  ENABLE VALIDATE);
