CREATE TABLE XXMIP.XLS_GLOBAL_INTERFACE_LINES
(
  HEADER_ID          NUMBER,
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATE_LOGIN  NUMBER,
  ATTRIBUTE1         VARCHAR2(4000 BYTE),
  ATTRIBUTE2         VARCHAR2(4000 BYTE),
  ATTRIBUTE3         VARCHAR2(4000 BYTE),
  ATTRIBUTE4         VARCHAR2(4000 BYTE),
  ATTRIBUTE5         VARCHAR2(4000 BYTE),
  ATTRIBUTE6         VARCHAR2(4000 BYTE),
  ATTRIBUTE7         VARCHAR2(4000 BYTE),
  ATTRIBUTE8         VARCHAR2(4000 BYTE),
  ATTRIBUTE9         VARCHAR2(4000 BYTE),
  ATTRIBUTE10        VARCHAR2(4000 BYTE),
  ATTRIBUTE11        VARCHAR2(4000 BYTE),
  ATTRIBUTE12        VARCHAR2(4000 BYTE),
  ATTRIBUTE13        VARCHAR2(4000 BYTE),
  ATTRIBUTE14        VARCHAR2(4000 BYTE),
  ATTRIBUTE15        VARCHAR2(4000 BYTE),
  ATTRIBUTE16        VARCHAR2(4000 BYTE),
  ATTRIBUTE17        VARCHAR2(4000 BYTE),
  ATTRIBUTE18        VARCHAR2(4000 BYTE),
  ATTRIBUTE19        VARCHAR2(4000 BYTE),
  ATTRIBUTE20        VARCHAR2(4000 BYTE),
  ATTRIBUTE21        VARCHAR2(4000 BYTE),
  ATTRIBUTE22        VARCHAR2(4000 BYTE),
  ATTRIBUTE23        VARCHAR2(4000 BYTE),
  ATTRIBUTE24        VARCHAR2(4000 BYTE),
  ATTRIBUTE25        VARCHAR2(4000 BYTE),
  LINE_NUM           NUMBER,
  INTERFACE_LINE_ID  NUMBER,
  SUCCESS_FLAG       VARCHAR2(1 BYTE),
  ERROR_MSG          VARCHAR2(4000 BYTE)
)
TABLESPACE XXMIP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.XLS_GLOBAL_INTERFACE_LINES_PK ON XXMIP.XLS_GLOBAL_INTERFACE_LINES
(INTERFACE_LINE_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.XLS_LINE_U1 ON XXMIP.XLS_GLOBAL_INTERFACE_LINES
(HEADER_ID, LINE_NUM)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XXMIP.XLS_GLOBAL_INTERFACE_LINES ADD (
  CONSTRAINT XLS_GLOBAL_INTERFACE_LINES_PK
  PRIMARY KEY
  (INTERFACE_LINE_ID)
  USING INDEX XXMIP.XLS_GLOBAL_INTERFACE_LINES_PK
  ENABLE VALIDATE);

ALTER TABLE XXMIP.XLS_GLOBAL_INTERFACE_LINES ADD (
  CONSTRAINT FK_HEADER 
  FOREIGN KEY (HEADER_ID) 
  REFERENCES XXMIP.XLS_GLOBAL_HEADER_INTERFACE (HEADER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
