CREATE TABLE XXMIP.XXMIP_CANCEL_AR_INV_BATCH
(
  FILE_ID               NUMBER,
  FILE_NAME             VARCHAR2(150 BYTE),
  REQUEST_ID            NUMBER,
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  PROCESSED_FLAG        VARCHAR2(1 BYTE),
  XLS_FILE              BLOB,
  DESCRIPTION           VARCHAR2(500 BYTE),
  TOTAL_NUMBER_OF_ROWS  NUMBER,
  NUMBER_OF_ERROR_ROWS  NUMBER
)
LOB (XLS_FILE) STORE AS BASICFILE (
  TABLESPACE  SYSTEM
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          16K
                  NEXT             3784K
                  MINEXTENTS       1
                  MAXEXTENTS       505
                  PCTINCREASE      50
                  FREELISTS        1
                  FREELIST GROUPS  1
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             40K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXMIP.XXMIP_CANCEL_AR_INV_BATCH_PK ON XXMIP.XXMIP_CANCEL_AR_INV_BATCH
(FILE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER XXMIP.XXMIP_CANCEL_AR_INV_BATCH_TRG
   BEFORE INSERT
   ON XXMIP.XXMIP_CANCEL_AR_INV_BATCH
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DISABLE
BEGIN
   -- For Toad:  Highlight column FILE_ID
   :new.FILE_ID := XXMIP_CANCEL_AR_INV_BATCH_SEQ.NEXTVAL;
END XXMIP_CANCEL_AR_INV_BATCH_TRG;
/


CREATE OR REPLACE SYNONYM APPS.XXMIP_CANCEL_AR_INV_BATCH FOR XXMIP.XXMIP_CANCEL_AR_INV_BATCH;


ALTER TABLE XXMIP.XXMIP_CANCEL_AR_INV_BATCH ADD (
  CONSTRAINT XXMIP_CANCEL_AR_INV_BATCH_PK
  PRIMARY KEY
  (FILE_ID)
  USING INDEX XXMIP.XXMIP_CANCEL_AR_INV_BATCH_PK
  ENABLE VALIDATE);
