CREATE TABLE XXMIP.XXMIP_CREDIT_MEMO_INTERFACE
(
  HEADER_ID          NUMBER                     NOT NULL,
  INTERFACE_LINE_ID  NUMBER                     NOT NULL,
  TRX_NUMBER         VARCHAR2(150 BYTE)         NOT NULL,
  SOB                NUMBER,
  TRX_LINE_DESC      VARCHAR2(500 BYTE),
  TRX_LINE_NUM       NUMBER                     NOT NULL,
  CM_TRX_DATE        DATE                       NOT NULL,
  CM_PAPER_NUMBER    VARCHAR2(250 BYTE)         NOT NULL,
  CM_CURRENCY_RATE   NUMBER                     NOT NULL,
  CM_NOTE            VARCHAR2(500 BYTE),
  CM_LINE_ITEM       VARCHAR2(250 BYTE),
  CM_LINE_DESC       VARCHAR2(500 BYTE)         NOT NULL,
  QUANTITY           NUMBER                     NOT NULL,
  UNIT_PRICE         NUMBER                     NOT NULL,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  API_MSG            VARCHAR2(500 BYTE),
  IS_PROCESSED       VARCHAR2(1 BYTE),
  SUCCESS_FLAG       VARCHAR2(1 BYTE),
  CUSTOMER_TRX_ID    NUMBER,
  CM_TRX_ID          NUMBER,
  CM_RATE_DATE       DATE,
  CURRENCY_CODE      VARCHAR2(50 BYTE)
)
TABLESPACE XXMIP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX XXMIP.CM_DATA_UIX ON XXMIP.XXMIP_CREDIT_MEMO_INTERFACE
(HEADER_ID, TRX_NUMBER, SOB, TRX_LINE_NUM)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX XXMIP.XXMIP_CREDIT_MEMO_INTERFACE_PK ON XXMIP.XXMIP_CREDIT_MEMO_INTERFACE
(INTERFACE_LINE_ID)
LOGGING
TABLESPACE XXMIP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM APPS.XXMIP_CREDIT_MEMO_INTERFACE FOR XXMIP.XXMIP_CREDIT_MEMO_INTERFACE;


ALTER TABLE XXMIP.XXMIP_CREDIT_MEMO_INTERFACE ADD (
  CONSTRAINT XXMIP_CREDIT_MEMO_INTERFACE_PK
  PRIMARY KEY
  (INTERFACE_LINE_ID)
  USING INDEX XXMIP.XXMIP_CREDIT_MEMO_INTERFACE_PK
  ENABLE VALIDATE);
